title: Cinepocalypse
description: "Film reviews by Ian Hirschfeld."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cinepocalypse.com" # the base hostname & protocol for your site, e.g. http://example.com
email: ian@cinepocalypse.com
twitter_username: cinepocalypse_
personal_twitter_username: ianhirschfeld
google_analytics: "UA-11359166-13"
typekit: hai2oqv
date_format: "%b %d, %Y"
open_graph_image: "OpenGraph.png"
markdown: kramdown
permalink: /:slug
plugins:
  - jekyll-feed
  - jekyll-sitemap
